update User Management tab
khengyun/FFood-shop pull request #62
Opened 2023-10-19 04:01 UTC by huynhkhachuy

2023-10-19 04:57 UTC, khengyun commented
many conflic. ☠️☠️

2023-10-19 13:25 UTC, tien-thanh-hua commented on nb-configuration.xml
Please add this file to .gitignore so that it may not affect other people's Netbeans configuration (it may or may not break their workflows). I use Intellij IDEA though, so I don't really care lmao

If adding this to .gitignore still does not ignore this file, just uncheck this file before you commit and push anything.

2023-10-19 13:54 UTC, tien-thanh-hua commented on src/main/webapp/assets/js/dataTablesConfig.js
Since user management table has too few columns (and their values are expected to be unique), having a filter (searchPane) is unnecessary. You can remove it.

Line 242 has a serious bug that can cause a page freeze if users continuously click the same tab link too many times.

Check my previous commit on how to fix it:
https://github.com/khengyun/FFood-shop/commit/db466e91741dfef6d66ba7dbc8203567ca6cc7d1

2023-10-19 14:06 UTC, tien-thanh-hua commented on src/main/webapp/WEB-INF/jspf/admin/order.jspf
Possible duplicate of staff/order.jspf. Considering keeping only 1 at a time (I think keeping the one in staff seems better than this one), and point all references of this file to the one in staff folder.

2023-10-19 14:13 UTC, tien-thanh-hua commented on src/main/webapp/WEB-INF/jspf/admin/user.jspf
Possible duplicate of staff/user.jspf, with added AI-generated code. The JS code here is unnecessary, DataTables already has built-in per-column sorting functions.

Keep either this file or the one in staff folder (I prefer this one), but not both. Point all references of this file to the one in staff folder, and vice versa.

2023-10-19 14:23 UTC, tien-thanh-hua requested changes
Too many duplicate .jspf files from /admin, tabs, and components alike. Please keep only 1 copy of each file, and remove the other one (remember to point all references of that removed duplicate file to the remaining file).

**VERY IMPORTANT**: 
- For .jspf files whose functions are shared by both admins and staff, put those files in /staff.
- Those that are unique to admin should be obviously put in /admin.
- Example: admins and staff can both add foods, so addFood.jspf should be placed in /staff. admin.jsp must `@include` the one in /staff instead of using a duplicate file like what you did here.

2023-10-21 07:44 UTC, quzanh1130 approved these changes

2023-10-21 07:44 UTC, quzanh1130 approved these changes

2023-10-23 08:15 UTC, khengyun commented on src/main/webapp/WEB-INF/jspf/admin/order.jspf
> +                    </td>
tes tesst commit

2023-10-26 10:31 UTC, closed without merging